FROM fholzer/nginx-brotli:v1.30.0

# Path to host app-specific configs + our general xh.conf. All configs copied in here are included
# by the standard $XH_NGINX_CONFIG_FILE (above) or could be selectively included by a custom file.
ENV XH_NGINX_CONFIG_PATH=/etc/nginx/conf.d

# Path to host include partials.
ENV XH_NGINX_CONFIG_INCL_PATH=/etc/nginx/includes

# Path to host the static JS/CSS/HTML content itself, copied from the client-side build.
ENV XH_NGINX_CONTENT_PATH=/usr/share/nginx/html

# Clear out default nginx config and welcome page
RUN rm $XH_NGINX_CONFIG_PATH/default.conf && rm $XH_NGINX_CONTENT_PATH/*

# Copy in overridden nginx-brotli.conf (brotli-flavored), xh-brotli.conf (brotli-flavored, with
# gzip directives commented out since they are set at the http level by nginx-brotli.conf above),
# and shared includes.
COPY nginx-brotli.conf /etc/nginx/nginx.conf
COPY xh-brotli.conf $XH_NGINX_CONFIG_PATH/xh.conf
COPY includes $XH_NGINX_CONFIG_INCL_PATH/
