# Standardized XH-specific nginx settings. This config partial is copied into $XH_NGINX_CONFIG_PATH
# within this project's Dockerfile. From there it is included within the top-level `http` block,
# typically alongside an `app.conf` config file provided by the app (with app-specific location
# blocks and other settings).

# Support compression for both static assets and proxy calls.
gzip on;
gzip_static on;
gzip_comp_level 2;
gzip_min_length 1000;
gzip_proxied any;
gzip_types application/json application/javascript text/css text/javascript;

# Increase client max body size to allow for larger uploads.
client_max_body_size 100m;

# Increase proxy headers hash size due to our use of proxy_set_header - as per nginx msg in log.
proxy_headers_hash_max_size 1024;

# Set a dynamic $expires var for use in app-level confs.
# - Cache JS/CSS assets indefinitely. New builds will have new filenames due to hoist-dev-utils bundling configs.
# - Ensure HTML pages (index.html entry point files) are *not* cached.
map $sent_http_content_type $expires {
    default                 off;
    application/javascript  max;
    font/woff2              max;
    image/png               max;
    text/css                max;
    text/html               "no-cache, no-store, must-revalidate";
}

# Determine the device type via UA sniffing for setting $is_desktop, $is_mobile, and $is_tablet vars, which can then
# be used in app.conf files to redirect root (/) to a platform-appropriate default client app (e.g. /app/ or /mobile/).
# Snagged from https://gist.github.com/perusio/1326701#gistcomment-2009231 and is not guaranteed by any means to be
# perfect or exhaustive. Apps should use with care - contact XH if your browser/device is misidentified.
map $http_user_agent $ua_device {
	default 'desktop';
	~*(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge\ |maemo|midp|mmp|mobile.+firefox|netfront|opera\ m(ob|in)i|palm(\ os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows\ ce|xda|xiino/i 'mobile';
	~*android|ipad|playbook|silk/i 'tablet';
}

map $ua_device $is_mobile {
    default 0;
    mobile 1;
}

map $ua_device $is_tablet {
    default 0;
    tablet 1;
}

map $ua_device $is_desktop {
    default 0;
    desktop 1;
}

# Support for legacy NTLM SSO via the Jespa library, a multi-step handshake that relies on a special Jespa-Connection-Id
# header to identify the client connection across multiple requests. This map sets a new $xh_jespa_connection_id for use
# in xh-proxy.conf, where the resulting value is used to add/replace the required header. If request arrives with the
# header already set, re-use that value as it is assumed to have been set by an upstream proxy/ingress using actual
# client addr and port. Otherwise, below uses the addr/port as known to nginx.
map $http_jespa_connection_id $xh_jespa_connection_id {
    volatile;
    default $http_jespa_connection_id;

    ""      $remote_addr:$remote_port;
}

# Ensure UTF8 charset spec'd in header, including for CSS files (which would not get a charset header by default).
# See https://github.com/xh/xh-nginx/issues/9 - rendering issue with icons.
charset utf-8;
charset_types text/html text/css text/xml text/plain text/vnd.wap.wml application/javascript application/rss+xml;

# NOTE - app-level Dockerfiles must copy in an appropriate app.conf with a server directive to specify app entry
# points, headers, and a proxy configuration back to the Tomcat container. See Toolbox or ask XH for assistance.
